// types.js (For defining action types)
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT = 'LOGOUT';
export const CREATE_PASSWORD_SUCCESS = 'CREATE_PASSWORD_SUCCESS';
export const CREATE_PASSWORD_FAILURE = 'CREATE_PASSWORD_FAILURE';
export const OTP_SENT = 'OTP_SENT';
export const OTP_FAILURE = 'OTP_FAILURE';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAILURE = 'RESET_PASSWORD_FAILURE';
export const OVERVIEW_SUCCESS = 'OVERVIEW_SUCCESS';
export const UPDATE_SUCCESS = 'UPDATE_SUCCESS';
export const VIS_UPDATE_SUCCESS = 'VIS_UPDATE_SUCCESS';
export const VALIDATE_FAILURE = 'VALIDATE_FAILURE';
export const VALIDATE_SUCCESS = 'VALIDATE_SUCCESS';
export const SET_VIS_DATA = 'SET_VIS_DATA';